swagger: "2.0"
info:
  title: A User API
  description: User Api
  version: 1.0.0
host: localhost:80
schemes:
  - http
basePath: /api/users
tags:
  - name:  user details
    description: display details of the users
paths:
  /users:
    get:
      tags:
        -ALL USERS
      summary:
        retrieve all users
      security:
        - []
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - create new user
      summary:
        create a new user
      security:
        - []
      responses:
        '201':
          description: created new resource

